/* eslint-disable @eslint-community/eslint-comments/disable-enable-pair -- auto generated */

/* eslint-disable @eslint-community/eslint-comments/no-unlimited-disable  -- auto generated */

/* eslint-disable -- auto generated  */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root';
import { Route as StakeRouteImport } from './app/stake';
import { Route as ProfileRouteImport } from './app/profile';
import { Route as LeaderboardRouteImport } from './app/leaderboard';
import { Route as GameRouteImport } from './app/game';
import { Route as IndexRouteImport } from './app/index';

const StakeRoute = StakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any);
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any);
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/game': typeof GameRoute;
  '/leaderboard': typeof LeaderboardRoute;
  '/profile': typeof ProfileRoute;
  '/stake': typeof StakeRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/game': typeof GameRoute;
  '/leaderboard': typeof LeaderboardRoute;
  '/profile': typeof ProfileRoute;
  '/stake': typeof StakeRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/game': typeof GameRoute;
  '/leaderboard': typeof LeaderboardRoute;
  '/profile': typeof ProfileRoute;
  '/stake': typeof StakeRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/game' | '/leaderboard' | '/profile' | '/stake';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/game' | '/leaderboard' | '/profile' | '/stake';
  id: '__root__' | '/' | '/game' | '/leaderboard' | '/profile' | '/stake';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  GameRoute: typeof GameRoute;
  LeaderboardRoute: typeof LeaderboardRoute;
  ProfileRoute: typeof ProfileRoute;
  StakeRoute: typeof StakeRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stake': {
      id: '/stake';
      path: '/stake';
      fullPath: '/stake';
      preLoaderRoute: typeof StakeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/leaderboard': {
      id: '/leaderboard';
      path: '/leaderboard';
      fullPath: '/leaderboard';
      preLoaderRoute: typeof LeaderboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/game': {
      id: '/game';
      path: '/game';
      fullPath: '/game';
      preLoaderRoute: typeof GameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  StakeRoute: StakeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
